import json
import os
from typing import Any, Dict, List, Optional
from dotenv import load_dotenv
import google.generativeai as genai
from pydantic import ValidationError

from app.models.verification import AnalyticalClaim

load_dotenv()


class ClaimExtractorConfigurationError(Exception):
    """Raised when required claim extractor configuration (such as GEMINI_API_KEY) is missing."""
    pass


class ClaimExtractionError(Exception):
    """Raised when claim extraction fails due to invalid inputs, API failures, or schema mismatches."""
    pass


CLAIM_EXTRACTOR_SYSTEM_INSTRUCTION = """You are the claim extraction component of VeriLens AI.
Your job is to read a natural-language analytical explanation and extract the core factual, testable analytical claims into structured JSON.

Strict Rules:
1. Extract ONLY claims explicitly stated in the analytical explanation text.
2. Do NOT invent claims, extrapolate unmentioned facts, or perform calculations.
3. Do NOT attempt to verify whether a claim is true or false.
4. Do NOT correct or critique the narrator.
5. Ignore conversational filler, greetings, or meta-comments that are not analytical claims.
6. If no analytical claims are present, return an empty array: {"claims": []}.
7. Return ONLY valid JSON matching the exact schema below.

Allowed comparison types:
- "highest"
- "lowest"
- "equal"
- "greater_than"
- "less_than"
- "greater_than_or_equal"
- "less_than_or_equal"
(or null if no explicit comparison is asserted).

JSON Output Schema:
{
  "claims": [
    {
      "subject": "EntityName" or null,
      "metric": "MetricName",
      "value": numeric_value or null,
      "comparison": "highest" | "lowest" | "equal" | "greater_than" | "less_than" | "greater_than_or_equal" | "less_than_or_equal" or null,
      "group_by": "DimensionName" or null
    }
  ]
}
"""


class ClaimExtractorService:
    """
    Extracts atomic, verifiable AnalyticalClaim objects from natural-language
    narrator explanations using Gemini.
    """

    def __init__(
        self,
        api_key: Optional[str] = None,
        model_name: Optional[str] = None
    ):
        self.api_key = api_key or os.getenv("GEMINI_API_KEY")
        self.model_name = model_name or os.getenv("GEMINI_MODEL", "gemini-2.5-flash")

    def _ensure_configured(self) -> None:
        """Validates that the Gemini API key is configured."""
        if not self.api_key:
            raise ClaimExtractorConfigurationError(
                "GEMINI_API_KEY is not configured. Please set GEMINI_API_KEY "
                "in your .env file or environment variables."
            )
        genai.configure(api_key=self.api_key)

    @staticmethod
    def _clean_json_text(text: str) -> str:
        """Strips markdown code fences from the raw LLM response text."""
        cleaned = text.strip()
        if cleaned.startswith("```json"):
            cleaned = cleaned[7:]
        elif cleaned.startswith("```"):
            cleaned = cleaned[3:]
        if cleaned.endswith("```"):
            cleaned = cleaned[:-3]
        return cleaned.strip()

    def _build_prompt(self, explanation: str, question: Optional[str] = None) -> str:
        """Constructs prompt for Gemini claim extraction."""
        prompt = f"""Natural-Language Explanation:
\"{explanation.strip()}\"
"""
        if question and question.strip():
            prompt += f"""
Contextual User Question:
\"{question.strip()}\"
"""
        prompt += """
Extract all atomic analytical claims from the explanation above into strict JSON.
Adhere strictly to the required schema {"claims": [...]}.
"""
        return prompt

    def extract_claims(
        self,
        explanation: str,
        question: Optional[str] = None
    ) -> List[AnalyticalClaim]:
        """
        Extracts structured AnalyticalClaim objects from narrator text.

        Args:
            explanation: The natural language explanation generated by NarratorService.
            question: Optional user question for contextual constraint.

        Returns:
            List of validated AnalyticalClaim instances.

        Raises:
            ClaimExtractorConfigurationError: When GEMINI_API_KEY is missing.
            ClaimExtractionError: When input is empty, API call fails, or JSON is invalid.
        """
        if not explanation or not explanation.strip():
            raise ClaimExtractionError("Explanation cannot be empty.")

        self._ensure_configured()
        prompt = self._build_prompt(explanation, question)

        try:
            model = genai.GenerativeModel(
                model_name=self.model_name,
                system_instruction=CLAIM_EXTRACTOR_SYSTEM_INSTRUCTION,
                generation_config={"response_mime_type": "application/json"}
            )
            response = model.generate_content(prompt)
            raw_text = response.text
            if not raw_text or not raw_text.strip():
                raise ClaimExtractionError("Received empty response from Gemini during claim extraction.")
        except ClaimExtractionError:
            raise
        except Exception as e:
            raise ClaimExtractionError(f"Error calling Gemini API for claim extraction: {e}") from e

        cleaned_json = self._clean_json_text(raw_text)

        try:
            data = json.loads(cleaned_json)
        except json.JSONDecodeError as err:
            raise ClaimExtractionError(
                f"Failed to parse Gemini output as JSON: {err}. Raw output was: {raw_text}"
            ) from err

        if not isinstance(data, dict) or "claims" not in data or not isinstance(data["claims"], list):
            raise ClaimExtractionError(
                f"Gemini response did not contain a valid 'claims' list. Parsed data: {data}"
            )

        validated_claims: List[AnalyticalClaim] = []
        for idx, item in enumerate(data["claims"]):
            if not isinstance(item, dict):
                raise ClaimExtractionError(
                    f"Invalid claim item at index {idx}: expected dict, got {type(item).__name__}"
                )
            try:
                claim = AnalyticalClaim.model_validate(item)
                validated_claims.append(claim)
            except ValidationError as err:
                raise ClaimExtractionError(
                    f"Claim at index {idx} does not conform to AnalyticalClaim schema: {err}"
                ) from err

        return validated_claims
